title: Shellcode Execution Under Carbon Black & Cortex XDR
email: rwhitcroft@dbg
description: 
markdown: kramdown
baseurl: ""
url: ""
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
